USE master
GO
CREATE DATABASE [DB]
GO
USE [DB]

CREATE TABLE [DB].[ALUMNO] 
(
    [ALUMNO_ID]         INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    [TARJETA_ID]        VARCHAR(50) NOT NULL,
    [NOMBRE]            VARCHAR(50) NOT NULL,
)

CREATE TABLE [DB].[REPORTE]
(
    [REPORTE_ID]        INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    [ALUMNO_ID]         INT NOT NULL FOREIGN KEY REFERENCES [DB].[ALUMNO]([ALUMNO_ID]),
    [FECHA]             DATETIME NOT NULL,
    [ALCOHOL]           DECIMAL NOT NULL,
    [ENTRADA]           VARCHAR(50) NOT NULL,
)
